name: ubuntu-raspi2-kernel
version: 4.8.0
summary: The Raspberry Pi 2/3 kernel for snappy
description: This is a snapped kernel, based off the yakkety raspi2 branch and config
type: kernel

parts:
  kernel:
    plugin: kernel
    source: .
    source-type: git
    kdefconfig: ['--makefile=debian/snapcraft.mk', 'branch=raspi2','flavour=raspi2', 'config']
    kconfigs:
      - CONFIG_LOCALVERSION="-yakkety_raspi2"
      - CONFIG_DEBUG_INFO=n
    kernel-image-target: zImage
